# Generated by Django 6.0.1 on 2026-02-27 12:06

import web.models.character
import web.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background_image',
            field=models.ImageField(default='user/background_images/default.png', upload_to=web.models.user.background_image_upload_to),
        ),
        migrations.AlterField(
            model_name='character',
            name='background_image',
            field=models.ImageField(blank=True, default='character/background_images/default.png', null=True, upload_to=web.models.character.background_image_upload_to),
        ),
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(default='character/photos/default.png', upload_to=web.models.character.photo_upload_to),
        ),
    ]
