# Generated by Django 6.0.1 on 2026-03-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_systemprompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemprompt',
            old_name='prompts',
            new_name='prompt',
        ),
    ]
